# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Numbers
  description: Numbers section
  icon: poll
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
  numbers:
    - heading: ""
      body: ""
  background_color:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
