# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Blog Feed"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: Our Latest Sustainability Resources
  body: "Dive deep into the world of sustainable energy with the latest articles, trends, and breakthroughs. At Essentia, we believe in empowering our community with knowledge. Stay informed, stay sustainable, and join the conversation shaping our energy future."
  button:
    button_url: /blog/
    button_text: View All Posts
    open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
