# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Intro
  description: Generic intro content block
  icon: wysiwyg
  tags:
    - Text

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  body: ""
  button:
    enabled: false
    button_url: 
    button_text: 
    open_in_new_tab: false
  background_color:
  text_align: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  body:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
