# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: heading
  description:
  icon: poll
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: 
  numbers:
    - heading: Our Mission
      body: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.
    - heading: Vision
      body: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.
    - heading: Our Approach
      body: llum similique ducimus accusamus laudantium praesentium, impedit quaerat,
        itaque maxime sunt deleniti voluptas distinctio.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
